show_link = ["user1"]

[general]
prefer_ipv6 = false
fast_mode = true
use_middle_proxy = false

[general.modes]
classic = false 
secure = false 
tls = true 

[server]
port = 443
listen_addr_ipv4 = "0.0.0.0"
listen_addr_ipv6 = "::"

[censorship]
tls_domain = "https://ya.ru/   # домен для SNI (пример! см. ниже)
mask = true # Включает проксирование реального сайта
mask_port = 443
fake_cert_len = 2048

[access.users]
user1 = "ВАШ_СЕКРЕТ_ИЗ_ШАГА_2"

[[upstreams]]
type = "direct"
enabled = true
weight = 10